name = "peruvian-holiday-api"
main = "src/index.ts"
compatibility_date = "2023-01-01"

[build]
command = "bun run build"

[build.upload]
format = "modules"

[[routes]]
pattern = "*"
script = "src/index.ts"